version: 0.0.{build}
build:
  project: Datapack-Code-Editor.sln
  verbosity: minimal
deploy:
- provider: GitHub
  description: A Datapack Code Editor
  auth_token:
    secure: 359OUESRLLHVdosaxi2mgvQxvSeYRmmH2LKmkarI/1PJE2tr1uZMH5NodOacqMAn
  artifact: Datapack_Editor
  configuration: Release
  prerelease: true
environment:
  auth_token:
    secure:'mbgPeg6VB7oIYlnLQNd4XDi5/i46y+O/xXNKsnfdFFusOJjfxS5F1U1yZISa3aGg=='

shallow_clone: true
image: Visual Studio 2019
build_script:
  - '"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/devenv.exe" /Build Release "Datapack-Code-Editor.sln"'

artifacts:
- path: Datapack-Code-Editor\bin\Release\*.exe
  name: Datapack_Editor
